version: 2.44.2.{build}
configuration: Release
platform: x64

branches:
  only:
    - develop
    - master

skip_branch_with_pr: true
skip_tags: true

environment:
  global:
    KEY_1CV8T:
      secure: OolAVEKkEg1cGCpG/VK2FaM0LWrPgMR/Kn4nTLYyKR0=
    API_TOKEN:
      secure: 85XpT8I1bxRTZaiIA+co0b5GS05J2VOn7PzunkYlL40=

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      job_name: Windows

matrix:
  fast_finish: true

install:
  - git clone -q --branch=platform https://github.com/lintest/tools1c.git bin
  - cd bin
  - 7z x tools1c.part01.rar -p%KEY_1CV8T%
  - cd %APPVEYOR_BUILD_FOLDER%

  - git clone -q --branch=master https://github.com/lintest/GraphViz.git GraphViz
  - cd GraphViz
  - git submodule update --init
  - cd %APPVEYOR_BUILD_FOLDER%

  - git clone -q --branch=master https://github.com/libexpat/libexpat.git Expat
  - cd Expat
  - git checkout -b version R_2_2_10
  - mkdir build32
  - cd build32
  - cmake ../expat -A Win32 -DEXPAT_MSVC_STATIC_CRT=ON -DEXPAT_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../../GraphViz/windows/dependencies/libraries/x86/
  - cmake --build . --config Release --target INSTALL
  - cd ..
  - mkdir build64
  - cd build64
  - cmake ../expat -A x64 -DEXPAT_MSVC_STATIC_CRT=ON -DEXPAT_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../../GraphViz/windows/dependencies/libraries/x64/
  - cmake --build . --config Release --target INSTALL
  - cd %APPVEYOR_BUILD_FOLDER%

  - cd GraphViz/windows/dependencies/libraries/x86/lib
  - del expat.lib
  - ren libexpat*.lib expat.lib
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd GraphViz/windows/dependencies/libraries/x64/lib
  - del expat.lib
  - ren libexpat*.lib expat.lib
  - cd %APPVEYOR_BUILD_FOLDER%
  
init:
  - cmake --version
  - msbuild /version
  - echo.

build_script:
  - powershell -File manifest.ps1

  - mkdir build32
  - cd build32
  - cmake .. -A Win32 -DMySuffix2=32 -DVERSION="%APPVEYOR_BUILD_VERSION%" -DDATE="2020-12-07"
  - cmake --build . --config Release --target GraphViz1c
  - cd ..

  - mkdir build64
  - cd build64
  - cmake .. -A x64 -DMySuffix2=64 -DVERSION="%APPVEYOR_BUILD_VERSION%" -DDATE="2020-12-07"
  - cmake --build . --config Release --target GraphViz1c
  - cd ..

  - copy .\bin32\Release\libGraphViz1cWin32.dll .
  - copy .\bin64\Release\libGraphViz1cWin64.dll .
  - Powershell -File appveyor.ps1

for:
  - matrix:
      only:
        - job_name: Windows

    after_build:
      - appveyor PushArtifact AddIn.zip
      - mkdir database
      - bin\1cv8t.exe CREATEINFOBASE File=%CD%/database
      - bin\1cv8t.exe DESIGNER /F %CD%/database /LoadExternalDataProcessorOrReportFromFiles Example.xml GraphViz1c.epf /Out example.log

    artifacts:
      - path: AddIn.zip
      - path: GraphViz1c.epf
      - path: autotest.log
      - path: example.log

    deploy:
      - provider: GitHub
        auth_token:
          secure: v7P89NQ2I5+WGNNdhpFrZEt6OCTPf8A8VSC5rttZMXh3DJ2fTChNEjZ1Wvm3kfBt
        repository: lintest/GraphViz1c
        artifact: AddIn.zip, GraphViz1c.epf
        draft: true
        prerelease: true
        force_update: true
        on:
          branch: master
